### ISSUE TITLE
첫번째 액티비티에 지도 띄우기 

### ISSUE THREAD

**Issue by Zimins** [Myoung-jae-Kim/SelectFoods#1]
아무 api 나 써서 첫 화면에 지도를 표시하는 스펙 진행 필요

**Comment by AramMJAE** [comment]
AVD 에서 에러나는거 빨리 찾았으면 시간낭비 줄였는데 핸드폰 직접 연결해서 폰에서 작동 시키면 kakao api 이용해서 지도 제대로 작동하고, 지도 연동하는거 해보니까 음식 메뉴 선택하고 공유하기만 생각했는데 해당 음식 관련 음식점 주변에 마커해서 띄워보는것도 의미 있을듯

**Comment by Zimins** [comment]
관련 커밋에 대한 링크를 부탁드립니다.

**Comment by Zimins** [comment]
요로케 eb492d42b40a15f1bf25663ff8f91a68f131d6eb
