### ISSUE TITLE
현 위치 기준으로 주변 식당을 가져오는 클래스 만들기 

### ISSUE THREAD

**Issue by Zimins** [Myoung-jae-Kim/SelectFoods#4]
현재 위치를 특정 클래스에 넣으면, 특정 거리에 있는 식당 목록을 리턴하는 기능을 구현. 

ui 는 테스트용으로만 구현하고, 해당 클래스 자체에 집중 필요

**Comment by AramMJAE** [comment]
해당 issue 에 대한 pr 입니다. 시간 있을 때, 피드백 해주세요
8981ecf

**Comment by AramMJAE** [comment]
만들고 보니 이렇게 오래 걸릴게 아니였네...

**Comment by AramMJAE** [comment]
pr에서 코멘트 남겨준대로 사용 안되고 있는 코드랑 주석 전부 날리고 엑티비티 이름 수정 완료.
